image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  TERM: "linux"
  EDITOR: "vim"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    paths:
        - .cache/pip
        - venv/

stages:
    - build
    - test

build:
    stage: build
    script:
        - uname -a
        - apt-get update
        - apt-get install -y python3-enchant vim
        - python -V  # Print out python version for debugging
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - pip install pylint pydocstyle pyenchant pyte pytest

lint:
    stage: test
    script:
        - pylint -rn cobib test --disable=fixme,duplicate-code

doc:
    stage: test
    script:
        - pydocstyle --convention=google --match=".*\.py" cobib test

spell:
    stage: test
    script:
        - python <<< 'import enchant; print(enchant.list_dicts())'
        - pylint -rn cobib test --disable=all --enable=spelling
          --spelling-dict='en_US' --spelling-private-dict-file=.pylintdict

test:
    stage: test
    script:
        - git config --global user.email "cobib@cobib.org"
        - git config --global user.name "CoBib"
        - python -m pytest --verbose test
